name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker images
      run: |
        docker-compose build
        docker-compose push

    - name: Run static analysis
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          sonar-scanner
          -Dsonar.organization=jsaffe  # Your SonarCloud organization key
          -Dsonar.projectKey=sonarcloud  # Your SonarCloud project key
          -Dsonar.sources=.
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}  # Ensure SONAR_TOKEN is set as a secret in your repository 

    - name: Deploy to test environment
      run: docker-compose up -d
