name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker images
      run: |
        docker-compose build
        docker-compose push

    - name: Run static analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        echo ${SONAR_TOKEN} # This is just to ensure the token is set, it will be masked in the logs
        sonar-scanner \
          -Dsonar.organization=jsaffe \
          -Dsonar.projectKey=sonarcloud \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${SONAR_TOKEN}

    - name: Deploy to test environment
      run: docker-compose up -d
