name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  static_scan_frontend:
    name: SonarCloudScan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: frontend/
          args: >
            -Dsonar.organization=jsaffe
            -Dsonar.projectKey=jsaffe_sonarcloud
            -Dsonar.token=$SONAR_TOKEN          
          
  static_scan_backend:
    name: SonarCloudScan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: backend/
          args: >
            -Dsonar.organization=jsaffe
            -Dsonar.projectKey=jsaffe_sonarcloud
            -Dsonar.token=$SONAR_TOKEN

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker images
      run: |
        docker-compose build
        docker-compose push
